//
//  ClipboardCapturePolicyTests.swift
//  KannuTests
//
//  Copyright (C) 2026 Kannu contributors
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

import XCTest

/// The clipboard history persists what it records, in plain text. A copy marked private by the
/// app that made it (a password manager, or Kannu itself copying a secret) must never enter it.
final class ClipboardCapturePolicyTests: XCTestCase {
    private let text = "public.utf8-plain-text"

    func testConcealedAndTransientCopiesAreNeverRecorded() {
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: [text, "org.nspasteboard.ConcealedType"]))
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: ["org.nspasteboard.TransientType", text]))
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: ["org.nspasteboard.ConcealedType"]),
                       "the marker alone is enough; it does not need to sit next to text")
    }

    func testOrdinaryCopiesAreRecorded() {
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: [text]))
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: ["public.png", "public.tiff"]))
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: []))
        // nspasteboard.org's third marker means "automatically generated", not "private".
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: [text, "org.nspasteboard.AutoGeneratedType"]))
    }

    /// `ClipboardManager` is not in the logic target, so the order of its capture is read from the
    /// source. The types are checked before the contents are read, and the change count is checked
    /// again after: the pasteboard is no snapshot, and a copy made mid-read could otherwise be
    /// recorded under the earlier decision (CodeRabbit on #71).
    func testTheCaptureChecksTypesFirstAndRechecksAfterReading() throws {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // KannuTests/
            .deletingLastPathComponent()   // repo root
            .appendingPathComponent("Kannu/managers/ClipboardManager.swift")
        let source = try String(contentsOf: url, encoding: .utf8)
        let start = try XCTUnwrap(source.range(of: "private func checkClipboard()"), "checkClipboard went away")
        let body = String(source[start.upperBound...].prefix(2000))
        let policy = try XCTUnwrap(body.range(of: "ClipboardCapturePolicy.shouldRecord(")?.lowerBound)
        let read = try XCTUnwrap(body.range(of: "getCurrentClipboardItem()")?.lowerBound)
        let recheck = try XCTUnwrap(body.range(of: "NSPasteboard.general.changeCount == currentChangeCount")?.lowerBound,
                                    "the capture no longer rechecks the pasteboard after reading it")
        let record = try XCTUnwrap(body.range(of: "addToHistory(")?.lowerBound)
        XCTAssertLessThan(policy, read, "the contents are read before the privacy markers are checked")
        XCTAssertLessThan(read, recheck)
        XCTAssertLessThan(recheck, record, "an item is recorded before the recheck")
    }
}
