//
//  ClipboardCapturePolicyTests.swift
//  KannuTests
//
//  Copyright (C) 2026 Kannu contributors
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

import XCTest

/// The clipboard history persists what it records, in plain text. A copy marked private by the
/// app that made it (a password manager, or Kannu itself copying a secret) must never enter it.
final class ClipboardCapturePolicyTests: XCTestCase {
    private let text = "public.utf8-plain-text"

    func testConcealedAndTransientCopiesAreNeverRecorded() {
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: [text, "org.nspasteboard.ConcealedType"]))
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: ["org.nspasteboard.TransientType", text]))
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: ["org.nspasteboard.ConcealedType"]),
                       "the marker alone is enough; it does not need to sit next to text")
    }

    func testOrdinaryCopiesAreRecorded() {
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: [text]))
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: ["public.png", "public.tiff"]))
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: []))
        // nspasteboard.org's third marker means "automatically generated", not "private".
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: [text, "org.nspasteboard.AutoGeneratedType"]))
    }
}
