//
//  ClipboardCapturePolicyTests.swift
//  KannuTests
//
//  Copyright (C) 2026 Kannu contributors
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

import XCTest

/// The clipboard history persists what it records, in plain text. A copy marked private by the
/// app that made it (a password manager, or Kannu itself copying a secret) must never enter it,
/// and neither must text holding an access token, which a token page copies with no marker.
final class ClipboardCapturePolicyTests: XCTestCase {
    private let text = "public.utf8-plain-text"

    func testConcealedAndTransientCopiesAreNeverRecorded() {
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: [text, "org.nspasteboard.ConcealedType"]))
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: ["org.nspasteboard.TransientType", text]))
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(types: ["org.nspasteboard.ConcealedType"]),
                       "the marker alone is enough; it does not need to sit next to text")
    }

    func testOrdinaryCopiesAreRecorded() {
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: [text]))
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: ["public.png", "public.tiff"]))
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: []))
        // nspasteboard.org's third marker means "automatically generated", not "private".
        XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(types: [text, "org.nspasteboard.AutoGeneratedType"]))
    }

    // MARK: - Token-shaped text

    /// A random-looking token body, built at run time like every fixture below, so no token-shaped
    /// literal sits in this file for a secret scanner (GitHub's push protection, Kannu's own hook
    /// watching an agent edit it) to trip on.
    private static func body(_ count: Int) -> String {
        let alphabet = Array("a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6q7R8s9T0")
        return String((0..<count).map { alphabet[$0 % alphabet.count] })
    }

    private static let gitlabToken = "glpat-" + body(20)
    private static let atlassianToken = "ATATT" + "3xFfGF0" + body(170) + "=" + "0A1B2C3D"
    private static let githubToken = "ghp_" + body(36)

    /// One sample per kind, at each format's minimum length where it has one.
    private static let samples: [(kind: String, token: String)] = [
        ("private_key", "-----BEGIN " + "OPENSSH PRIVATE KEY-----\n" + body(70) + "\n" + body(70)
            + "\n-----END " + "OPENSSH PRIVATE KEY-----"),
        ("anthropic_key", "sk-ant-" + "api03-" + body(90)),
        ("openai_key", "sk-" + "proj-" + body(48)),
        ("openai_key", "sk-" + body(32)),
        ("aws_access_key", "AKIA" + "Z7Q2M4XKP9RT3WY5"),
        ("aws_access_key", "ASIA" + "Q7Z2M4XKP9RT3WY5"),
        ("github_token", githubToken),
        ("github_token", "ghs_" + body(36)),
        ("github_token", "github_pat_" + body(22) + "_" + body(59)),
        ("gitlab_token", gitlabToken),
        ("slack_token", "xoxb-" + "1234567890" + "-" + body(24)),
        ("stripe_key", "sk" + "_live_" + body(24)),
        ("stripe_key", "rk" + "_live_" + body(24)),
        ("google_api_key", "AIza" + body(35)),
        ("npm_token", "npm_" + body(36)),
        ("huggingface_token", "hf_" + body(34)),
        ("atlassian_token", atlassianToken),
    ]

    func testEveryFormatIsCaughtAloneAndInsideASentence() {
        for (kind, token) in Self.samples {
            XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: token), kind, "\(kind) alone")
            XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: "my token is " + token + ", keep it safe"), kind,
                           "\(kind) inside a sentence")
            XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(text: token), kind)
        }
        let covered = Set(Self.samples.map { $0.kind })
        for format in ClipboardCapturePolicy.secretFormats {
            XCTAssertNotNil(format.regex, "\(format.kind)'s pattern does not compile")
            XCTAssertTrue(covered.contains(format.kind), "\(format.kind) has no sample here")
        }
    }

    /// A real token can have no digit: about 1 GitLab token in 20 to 30 and 1 AWS key ID in 30,
    /// and every Hugging Face token, which is letters only. The hook's digit rule lets those through;
    /// the clipboard must not, because what it misses it persists in plain text.
    func testTokensWithNoDigitAreCaught() {
        let letters = Array("qWeRtYuIoPaSdFgHjKlZxCvBnM")
        let random = { (count: Int) in String((0..<count).map { letters[($0 * 7) % letters.count] }) }
        let caught: [(kind: String, token: String)] = [
            ("gitlab_token", "glpat-" + random(20)),
            ("gitlab_token", "glpat-" + random(12) + "-" + random(7)),
            ("huggingface_token", "hf_" + random(34)),
            ("github_token", "ghp_" + random(36)),
            ("aws_access_key", "AKIA" + "ZQXKPRTWYMBNVCLJ"),
        ]
        for (kind, token) in caught {
            XCTAssertFalse(token.contains { $0.isNumber }, "\(kind): the sample must have no digit")
            XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: token), kind, kind)
            XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: "TOKEN=" + token + "\n"), kind, "\(kind) in a .env line")
        }
    }

    /// A private key copied short of its footer, or as a JSON string with its line breaks written
    /// "\n" (a Google Cloud service-account file), or with the legacy encrypted headers, is still
    /// a key.
    func testPrivateKeyBodiesAreCaughtWithoutTheFooterAndInsideJSON() {
        let header = "-----BEGIN " + "PRIVATE KEY-----"
        let caught = [
            header + "\n" + Self.body(64) + "\n" + Self.body(40),
            header + "\r\n" + Self.body(30) + "\r\n" + Self.body(34) + "\r\n",
            "{\"type\": \"service_account\", \"private_key\": \"" + header + "\\n" + Self.body(40) + "\\n"
                + Self.body(40) + "\\n-----END " + "PRIVATE KEY-----\\n\", \"client_email\": \"ci@example.com\"}",
            "-----BEGIN " + "RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,"
                + "0123456789ABCDEF0123456789ABCDEF\n\n" + Self.body(64) + "\n" + Self.body(64)
                + "\n-----END " + "RSA PRIVATE KEY-----",
            header + " " + Self.body(64) + " " + Self.body(64) + " -----END " + "PRIVATE KEY-----",
        ]
        for sample in caught {
            XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: sample), "private_key", sample)
        }
    }

    func testTextHoldingATokenOnAnyLineIsSkipped() {
        let env = "# Jira\nJIRA_BASE_URL=https://example.atlassian.net\nJIRA_EMAIL=me@example.com\n"
            + "JIRA_API_TOKEN=" + Self.atlassianToken + "\n"
        XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: env), "atlassian_token")

        let script = "#!/bin/sh\nset -e\ncurl --header \"PRIVATE-TOKEN: " + Self.gitlabToken
            + "\" https://gitlab.example.com/api/v4/projects\n"
        XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: script), "gitlab_token")

        let json = "{\n  \"github\": {\n    \"token\": \"" + Self.githubToken + "\"\n  }\n}"
        XCTAssertEqual(ClipboardCapturePolicy.secretKind(in: json), "github_token")

        let url = "https://gitlab.example.com/api/v4/projects?private_token=" + Self.gitlabToken
        XCTAssertFalse(ClipboardCapturePolicy.shouldRecord(text: url), "a copied URL is checked too")
    }

    func testNearMissesAreRecorded() {
        let nearMisses: [(String, String)] = [
            ("glpat-" + Self.body(19), "one short of GitLab's minimum"),
            ("ghp_" + Self.body(35), "one short of GitHub's minimum"),
            ("hf_" + Self.body(33), "one short of Hugging Face's minimum"),
            ("ATATT" + Self.body(99), "one short of the Atlassian minimum"),
            ("npm_" + Self.body(37), "npm tokens are exactly 36 characters"),
            ("AIza" + Self.body(36), "Google keys are exactly 35 characters"),
            ("AKIA" + "Z7Q2M4XKP9RT3WY5Q", "AWS key IDs are exactly 16 characters"),
            ("x" + Self.gitlabToken, "glued to the word before it"),
            ("id_" + Self.githubToken, "an underscore before it is part of the same word"),
            ("sk-ant-" + "EXAMPLE" + Self.body(40), "a documentation placeholder"),
            ("AKIAIOSFODNN7EXAMPLE", "AWS's own documentation key"),
            ("glpat-" + String(repeating: "x", count: 24), "a redacted token"),
            ("sk-" + String(repeating: "ab12", count: 10), "too few distinct characters to be random"),
            ("glpat-" + String(repeating: "a", count: 24), "one character repeated"),
            ("glpat-" + "your-token-goes-here", "lower-case words, not a random body"),
            ("xoxb-" + "your-bot-token-from-the-app-page", "lower-case words, not a random body"),
            ("sk-" + "learn-compatible-estimator-wrapper-for-pipelines", "lower-case words after a bare sk-"),
            ("-----BEGIN " + "PRIVATE KEY-----", "a private key header with no key"),
            ("-----BEGIN " + "RSA PRIVATE KEY-----\n-----END " + "RSA PRIVATE KEY-----", "an empty key block"),
        ]
        for (sample, why) in nearMisses {
            XCTAssertNil(ClipboardCapturePolicy.secretKind(in: sample), why)
            XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(text: sample), why)
        }
    }

    /// Prose and code that name a private key header are not a key, however many letters follow
    /// the header: key material is one base64 run, and a space or a quote ends it.
    func testTextThatOnlyNamesAPrivateKeyHeaderIsRecorded() {
        let mentions = [
            "Your key file begins with -----BEGIN " + "OPENSSH PRIVATE KEY----- . Never paste it into a chat, "
                + "a ticket or an email, and never commit it to a repository.",
            "Paste the block that starts with -----BEGIN " + "PRIVATE KEY----- into the field labelled Signing "
                + "Key and save the settings page before you continue.",
            "guard pem.hasPrefix(\"-----BEGIN " + "PRIVATE KEY-----\") else { throw KeyError.notPKCS8 }\n"
                + "let body = pem.components(separatedBy: .newlines).dropFirst().joined()",
            "if line.hasPrefix(\"-----BEGIN " + "RSA PRIVATE KEY-----\") { throw KeyError.unsupportedFormat("
                + "path: url.path, reason: \"convert it with ssh-keygen first\") }",
        ]
        for sample in mentions {
            let afterHeader = sample.components(separatedBy: "KEY-----")[1]
            XCTAssertGreaterThanOrEqual(afterHeader.filter { $0.isASCII && ($0.isLetter || $0.isNumber) }.count, 64,
                                        "the sample must hold enough letters to pass for a key body")
            XCTAssertNil(ClipboardCapturePolicy.secretKind(in: sample), sample)
            XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(text: sample), sample)
        }
    }

    func testOrdinaryTextIsRecorded() {
        let ordinary = [
            "",
            "Ask the desk-side team to review risk-assessment-for-quarterly-planning-cycle-2026 before "
                + "the task-force-sync-meeting-notes-2026-10-04 deadline.",
            "Atlassian API tokens start with ATATT, GitLab ones with glpat- and Slack ones with xoxb-.",
            "xoxo, see you on Monday",
            "let url = URL(string: \"https://gitlab.com/group/project/-/merge_requests/42\")",
            "e0f5d0e1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7",
            "6F9619FF-8B86-D011-B42D-00C04FC964FF",
            Self.body(200),
            "npm_config_cache=/tmp/npm and hf_hub_download(repo_id) and ASIAN markets",
        ]
        for sample in ordinary {
            XCTAssertNil(ClipboardCapturePolicy.secretKind(in: sample), sample)
            XCTAssertTrue(ClipboardCapturePolicy.shouldRecord(text: sample), sample)
        }
    }

    /// The check runs on the main thread for every copy, so a large copy dense with near misses
    /// must stay cheap: every pattern starts with a literal and has bounded repetition.
    func testAMegabyteOfNearMissesIsScannedQuickly() {
        let line = "the task-force-sync-meeting-notes-2026-10-04 and risk-assessment-for-quarterly-planning-2026, "
            + "xoxo AKIA npm_ hf_ ghp_ glpat- ATATT AIza sk_live_ PRIVATE KEY\n"
        let large = String(repeating: line, count: 1_000_000 / line.utf8.count + 1)
        let start = Date()
        XCTAssertNil(ClipboardCapturePolicy.secretKind(in: large))
        let elapsed = Date().timeIntervalSince(start)
        XCTAssertLessThan(elapsed, 1.0, "scanning 1 MB took \(elapsed) s")
    }

    /// The pattern list mirrors the hook script's, which is what tells Kannu about a secret in a
    /// prompt. A format added there and not here would reach the clipboard history unnoticed.
    func testTheFormatsMirrorTheHookScript() throws {
        let source = try String(contentsOf: Self.repoFile("Kannu/managers/AgentStatus/AgentHookInstaller.swift"),
                                encoding: .utf8)
        let start = try XCTUnwrap(source.range(of: "SEC_PATTERNS = ["), "the hook script's secret patterns moved")
        let block = source[start.upperBound...]
            .split(separator: "\n", omittingEmptySubsequences: false)
            .prefix { $0.trimmingCharacters(in: .whitespaces) != "]" }
            .joined(separator: "\n")
        let entry = try NSRegularExpression(pattern: #"\("([a-z_]+)", \(([^)]*)\),\s*"([^"]+)"\)"#)
        let matches = entry.matches(in: block, range: NSRange(block.startIndex..., in: block))
        XCTAssertGreaterThanOrEqual(matches.count, 11, "the hook's pattern list no longer parses")
        for match in matches {
            let field = { (index: Int) throws -> String in
                String(block[try XCTUnwrap(Range(match.range(at: index), in: block))])
            }
            let kind = try field(1)
            let format = try XCTUnwrap(ClipboardCapturePolicy.secretFormats.first { $0.kind == kind },
                                       "the hook looks for \(kind); the clipboard does not")
            XCTAssertEqual(format.anchors, try Self.quotedStrings(in: try field(2)), kind)
            XCTAssertEqual(format.pattern, try field(3), kind)
        }

        let prefixes = try Self.quotedStrings(after: "SEC_LITERAL_PREFIXES = (", in: source)
        XCTAssertFalse(prefixes.isEmpty)
        XCTAssertTrue(Set(prefixes).isSubset(of: ClipboardCapturePolicy.literalPrefixes), "\(prefixes)")
        XCTAssertEqual(try Self.quotedStrings(after: "SEC_PLACEHOLDER_WORDS = (", in: source),
                       ClipboardCapturePolicy.placeholderWords)
    }

    /// `ClipboardManager` is not in the logic target, so the order of its capture is read from the
    /// source. The types are checked before the contents are read, and the change count is checked
    /// again after: the pasteboard is no snapshot, and a copy made mid-read could otherwise be
    /// recorded under the earlier decision (CodeRabbit on #71). The text is checked for a token
    /// before anything is recorded.
    func testTheCaptureChecksTypesFirstAndRechecksAfterReading() throws {
        let source = try String(contentsOf: Self.repoFile("Kannu/managers/ClipboardManager.swift"), encoding: .utf8)
        let start = try XCTUnwrap(source.range(of: "private func checkClipboard()"), "checkClipboard went away")
        let body = String(source[start.upperBound...].prefix(2000))
        let policy = try XCTUnwrap(body.range(of: "ClipboardCapturePolicy.shouldRecord(types:")?.lowerBound)
        let read = try XCTUnwrap(body.range(of: "getCurrentClipboardItem()")?.lowerBound)
        let recheck = try XCTUnwrap(body.range(of: "NSPasteboard.general.changeCount == currentChangeCount")?.lowerBound,
                                    "the capture no longer rechecks the pasteboard after reading it")
        let textCheck = try XCTUnwrap(body.range(of: "ClipboardCapturePolicy.shouldRecord(text:")?.lowerBound,
                                      "the capture no longer checks the text for a token")
        let record = try XCTUnwrap(body.range(of: "addToHistory(")?.lowerBound)
        XCTAssertLessThan(policy, read, "the contents are read before the privacy markers are checked")
        XCTAssertLessThan(read, recheck)
        XCTAssertLessThan(recheck, record, "an item is recorded before the recheck")
        XCTAssertLessThan(read, textCheck)
        XCTAssertLessThan(textCheck, record, "an item is recorded before its text is checked for a token")
    }

    // MARK: - Helpers

    private static func repoFile(_ path: String) -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // KannuTests/
            .deletingLastPathComponent()   // repo root
            .appendingPathComponent(path)
    }

    private static func quotedStrings(in text: String) throws -> [String] {
        let quoted = try NSRegularExpression(pattern: #""([^"]*)""#)
        return quoted.matches(in: text, range: NSRange(text.startIndex..., in: text)).compactMap {
            Range($0.range(at: 1), in: text).map { String(text[$0]) }
        }
    }

    /// The quoted strings of a Python tuple that starts at `marker`.
    private static func quotedStrings(after marker: String, in source: String) throws -> [String] {
        let start = try XCTUnwrap(source.range(of: marker), "\(marker) moved")
        let end = try XCTUnwrap(source.range(of: ")", range: start.upperBound..<source.endIndex))
        return try quotedStrings(in: String(source[start.upperBound..<end.lowerBound]))
    }
}
